version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: food-api
    container_name: food-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 8000:8000
    depends_on:
      food-postgres:
        condition: service_healthy
    networks:
      - food-network
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=food-postgres
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  food-postgres:
    image: postgres
    container_name: food-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d food_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - food-network

volumes:
  postgres_data:

networks:
  food-network:
    driver: bridge